# Generated by Django 4.0.5 on 2022-10-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('lawyer_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('star_ratings', models.IntegerField(blank=True)),
            ],
        ),
    ]
