# Generated by Django 4.0.5 on 2022-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('lawyer_name', models.CharField(max_length=255)),
                ('metting_type', models.CharField(blank=True, max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('meeting_Status', models.CharField(default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('lawyer_name', models.CharField(max_length=255)),
                ('metting_type', models.CharField(blank=True, max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
    ]
