# Generated by Django 4.0.5 on 2022-08-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_rename_metting_type_meetingrequest_meeting_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='meeting_Location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meetings',
            name='meeting_Location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
