# Generated by Django 4.0.5 on 2022-10-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meetingrequest_meeting_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meetings',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
