# Generated by Django 4.0.5 on 2022-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('doc_image', models.ImageField(upload_to='lawyerDocs')),
            ],
        ),
    ]
