# Generated by Django 4.0.5 on 2022-06-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
