# Generated by Django 4.0.5 on 2022-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='doc_image',
            field=models.ImageField(blank=True, upload_to='lawyerDocs'),
        ),
    ]
