# Generated by Django 4.0.5 on 2022-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_alter_lawyer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='ph_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='ph_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
