# Generated by Django 4.0.5 on 2022-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_lawyer_ph_no_user_ph_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='type',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
